import type { Sentence } from './types';

export const sentences: Sentence[] = [
  // ===== Level 1: 초급 (id 1-70) - 기본 SVO, 단순 시제, 일상 표현 =====
  { id: 1, level: 1, korean: '나는 매일 아침에 커피를 마셔요.', wordOrder: ['나는 마셔요', '커피를', '매일 아침에'], hints: ['drink', 'coffee', 'every morning'], answer: 'I drink coffee every morning.' },
  { id: 2, level: 1, korean: '그녀는 학교에서 영어를 가르쳐요.', wordOrder: ['그녀는 가르쳐요', '영어를', '학교에서'], hints: ['teach', 'English', 'at school'], answer: 'She teaches English at school.' },
  { id: 3, level: 1, korean: '우리는 주말에 공원에 가요.', wordOrder: ['우리는 가요', '공원에', '주말에'], hints: ['go', 'to the park', 'on weekends'], answer: 'We go to the park on weekends.' },
  { id: 4, level: 1, korean: '그는 회사에서 컴퓨터를 사용해요.', wordOrder: ['그는 사용해요', '컴퓨터를', '회사에서'], hints: ['use', 'computer', 'at work'], answer: 'He uses a computer at work.' },
  { id: 5, level: 1, korean: '아이들이 운동장에서 축구를 해요.', wordOrder: ['아이들이 해요', '축구를', '운동장에서'], hints: ['play', 'soccer', 'playground'], answer: 'The children play soccer on the playground.' },
  { id: 6, level: 1, korean: '나는 점심에 보통 샌드위치를 먹어요.', wordOrder: ['나는 보통 먹어요', '샌드위치를', '점심에'], hints: ['usually', 'sandwich', 'for lunch'], answer: 'I usually eat a sandwich for lunch.' },
  { id: 7, level: 1, korean: '그녀는 매일 밤 책을 읽어요.', wordOrder: ['그녀는 읽어요', '책을', '매일 밤'], hints: ['read', 'book', 'every night'], answer: 'She reads a book every night.' },
  { id: 8, level: 1, korean: '우리 아버지는 아침에 신문을 읽으세요.', wordOrder: ['우리 아버지는 읽으세요', '신문을', '아침에'], hints: ['read', 'newspaper', 'in the morning'], answer: 'My father reads the newspaper in the morning.' },
  { id: 9, level: 1, korean: '나는 버스로 학교에 가요.', wordOrder: ['나는 가요', '학교에', '버스로'], hints: ['go', 'to school', 'by bus'], answer: 'I go to school by bus.' },
  { id: 10, level: 1, korean: '그는 저녁에 음악을 들어요.', wordOrder: ['그는 들어요', '음악을', '저녁에'], hints: ['listen to', 'music', 'in the evening'], answer: 'He listens to music in the evening.' },
  { id: 11, level: 1, korean: '나는 주말에 친구를 만나요.', wordOrder: ['나는 만나요', '친구를', '주말에'], hints: ['meet', 'friend', 'on weekends'], answer: 'I meet my friend on weekends.' },
  { id: 12, level: 1, korean: '그녀는 가게에서 옷을 사요.', wordOrder: ['그녀는 사요', '옷을', '가게에서'], hints: ['buy', 'clothes', 'at the store'], answer: 'She buys clothes at the store.' },
  { id: 13, level: 1, korean: '우리는 일요일에 교회에 가요.', wordOrder: ['우리는 가요', '교회에', '일요일에'], hints: ['go', 'to church', 'on Sundays'], answer: 'We go to church on Sundays.' },
  { id: 14, level: 1, korean: '그는 아침에 샤워를 해요.', wordOrder: ['그는 해요', '샤워를', '아침에'], hints: ['take', 'shower', 'in the morning'], answer: 'He takes a shower in the morning.' },
  { id: 15, level: 1, korean: '나는 물을 많이 마셔요.', wordOrder: ['나는 마셔요', '많은 물을'], hints: ['drink', 'a lot of', 'water'], answer: 'I drink a lot of water.' },
  { id: 16, level: 1, korean: '그녀는 피아노를 잘 쳐요.', wordOrder: ['그녀는 쳐요', '피아노를', '잘'], hints: ['play', 'piano', 'well'], answer: 'She plays the piano well.' },
  { id: 17, level: 1, korean: '우리 엄마는 요리를 잘하세요.', wordOrder: ['우리 엄마는 요리해요', '잘'], hints: ['cook', 'well'], answer: 'My mom cooks well.' },
  { id: 18, level: 1, korean: '그는 매일 운동을 해요.', wordOrder: ['그는 운동해요', '매일'], hints: ['exercise', 'every day'], answer: 'He exercises every day.' },
  { id: 19, level: 1, korean: '나는 고양이 두 마리를 키워요.', wordOrder: ['나는 키워요', '고양이 두 마리를'], hints: ['have', 'two cats'], answer: 'I have two cats.' },
  { id: 20, level: 1, korean: '그녀는 병원에서 일해요.', wordOrder: ['그녀는 일해요', '병원에서'], hints: ['work', 'at a hospital'], answer: 'She works at a hospital.' },
  { id: 21, level: 1, korean: '나는 한국 음식을 좋아해요.', wordOrder: ['나는 좋아해요', '한국 음식을'], hints: ['like', 'Korean food'], answer: 'I like Korean food.' },
  { id: 22, level: 1, korean: '그는 아주 빨리 달려요.', wordOrder: ['그는 달려요', '아주 빨리'], hints: ['run', 'very fast'], answer: 'He runs very fast.' },
  { id: 23, level: 1, korean: '우리는 같은 학교에 다녀요.', wordOrder: ['우리는 다녀요', '같은 학교에'], hints: ['go to', 'the same school'], answer: 'We go to the same school.' },
  { id: 24, level: 1, korean: '그녀는 긴 머리카락을 가지고 있어요.', wordOrder: ['그녀는 가지고 있어요', '긴 머리카락을'], hints: ['have', 'long hair'], answer: 'She has long hair.' },
  { id: 25, level: 1, korean: '나는 오늘 기분이 좋아요.', wordOrder: ['나는 느껴요', '기분이 좋게', '오늘'], hints: ['feel', 'good', 'today'], answer: 'I feel good today.' },
  { id: 26, level: 1, korean: '그는 새 차를 샀어요.', wordOrder: ['그는 샀어요', '새 차를'], hints: ['bought', 'a new car'], answer: 'He bought a new car.' },
  { id: 27, level: 1, korean: '나는 어제 영화를 봤어요.', wordOrder: ['나는 봤어요', '영화를', '어제'], hints: ['watched', 'a movie', 'yesterday'], answer: 'I watched a movie yesterday.' },
  { id: 28, level: 1, korean: '그녀는 지난주에 서울에 갔어요.', wordOrder: ['그녀는 갔어요', '서울에', '지난주에'], hints: ['went', 'to Seoul', 'last week'], answer: 'She went to Seoul last week.' },
  { id: 29, level: 1, korean: '우리는 저녁으로 피자를 먹었어요.', wordOrder: ['우리는 먹었어요', '피자를', '저녁으로'], hints: ['had', 'pizza', 'for dinner'], answer: 'We had pizza for dinner.' },
  { id: 30, level: 1, korean: '그는 숙제를 다 끝냈어요.', wordOrder: ['그는 끝냈어요', '그의 숙제를'], hints: ['finished', 'homework'], answer: 'He finished his homework.' },
  { id: 31, level: 1, korean: '나는 오늘 아침에 늦게 일어났어요.', wordOrder: ['나는 일어났어요', '늦게', '오늘 아침에'], hints: ['woke up', 'late', 'this morning'], answer: 'I woke up late this morning.' },
  { id: 32, level: 1, korean: '그녀는 편지를 썼어요.', wordOrder: ['그녀는 썼어요', '편지를'], hints: ['wrote', 'a letter'], answer: 'She wrote a letter.' },
  { id: 33, level: 1, korean: '우리는 해변에서 수영했어요.', wordOrder: ['우리는 수영했어요', '해변에서'], hints: ['swam', 'at the beach'], answer: 'We swam at the beach.' },
  { id: 34, level: 1, korean: '나는 내일 시험이 있어요.', wordOrder: ['나는 있어요', '시험이', '내일'], hints: ['have', 'an exam', 'tomorrow'], answer: 'I have an exam tomorrow.' },
  { id: 35, level: 1, korean: '그는 아침마다 조깅을 해요.', wordOrder: ['그는 조깅해요', '매일 아침'], hints: ['jog', 'every morning'], answer: 'He jogs every morning.' },
  { id: 36, level: 1, korean: '그녀는 카페에서 공부해요.', wordOrder: ['그녀는 공부해요', '카페에서'], hints: ['study', 'at a cafe'], answer: 'She studies at a cafe.' },
  { id: 37, level: 1, korean: '나는 형이 한 명 있어요.', wordOrder: ['나는 있어요', '형이 한 명'], hints: ['have', 'older brother'], answer: 'I have an older brother.' },
  { id: 38, level: 1, korean: '그들은 함께 저녁을 먹어요.', wordOrder: ['그들은 먹어요', '저녁을', '함께'], hints: ['eat', 'dinner', 'together'], answer: 'They eat dinner together.' },
  { id: 39, level: 1, korean: '나는 토요일에 청소를 해요.', wordOrder: ['나는 청소해요', '토요일에'], hints: ['clean', 'on Saturdays'], answer: 'I clean on Saturdays.' },
  { id: 40, level: 1, korean: '그녀는 예쁜 목소리를 가지고 있어요.', wordOrder: ['그녀는 가지고 있어요', '예쁜 목소리를'], hints: ['have', 'beautiful voice'], answer: 'She has a beautiful voice.' },
  { id: 41, level: 1, korean: '우리 개는 공원에서 뛰어요.', wordOrder: ['우리 개는 뛰어요', '공원에서'], hints: ['run', 'in the park'], answer: 'My dog runs in the park.' },
  { id: 42, level: 1, korean: '나는 겨울을 좋아해요.', wordOrder: ['나는 좋아해요', '겨울을'], hints: ['like', 'winter'], answer: 'I like winter.' },
  { id: 43, level: 1, korean: '그는 매일 일기를 써요.', wordOrder: ['그는 써요', '일기를', '매일'], hints: ['write', 'diary', 'every day'], answer: 'He writes a diary every day.' },
  { id: 44, level: 1, korean: '그녀는 빵을 자주 구워요.', wordOrder: ['그녀는 구워요', '빵을', '자주'], hints: ['bake', 'bread', 'often'], answer: 'She often bakes bread.' },
  { id: 45, level: 1, korean: '나는 지하철로 출근해요.', wordOrder: ['나는 가요', '출근', '지하철로'], hints: ['go', 'to work', 'by subway'], answer: 'I go to work by subway.' },
  { id: 46, level: 1, korean: '그는 영어를 잘해요.', wordOrder: ['그는 말해요', '영어를', '잘'], hints: ['speak', 'English', 'well'], answer: 'He speaks English well.' },
  { id: 47, level: 1, korean: '우리 선생님은 아주 친절해요.', wordOrder: ['우리 선생님은', '아주 친절해요'], hints: ['teacher', 'very kind'], answer: 'Our teacher is very kind.' },
  { id: 48, level: 1, korean: '나는 사과와 바나나를 샀어요.', wordOrder: ['나는 샀어요', '사과와 바나나를'], hints: ['bought', 'apples and bananas'], answer: 'I bought apples and bananas.' },
  { id: 49, level: 1, korean: '그녀는 택시를 탔어요.', wordOrder: ['그녀는 탔어요', '택시를'], hints: ['took', 'a taxi'], answer: 'She took a taxi.' },
  { id: 50, level: 1, korean: '우리는 함께 사진을 찍었어요.', wordOrder: ['우리는 찍었어요', '사진을', '함께'], hints: ['took', 'pictures', 'together'], answer: 'We took pictures together.' },
  { id: 51, level: 1, korean: '나는 방을 정리했어요.', wordOrder: ['나는 정리했어요', '내 방을'], hints: ['cleaned', 'my room'], answer: 'I cleaned my room.' },
  { id: 52, level: 1, korean: '그는 새 신발을 신고 있어요.', wordOrder: ['그는 신고 있어요', '새 신발을'], hints: ['wearing', 'new shoes'], answer: 'He is wearing new shoes.' },
  { id: 53, level: 1, korean: '그녀는 창문을 열었어요.', wordOrder: ['그녀는 열었어요', '창문을'], hints: ['opened', 'the window'], answer: 'She opened the window.' },
  { id: 54, level: 1, korean: '나는 매일 우유를 마셔요.', wordOrder: ['나는 마셔요', '우유를', '매일'], hints: ['drink', 'milk', 'every day'], answer: 'I drink milk every day.' },
  { id: 55, level: 1, korean: '그는 기타를 칠 수 있어요.', wordOrder: ['그는 칠 수 있어요', '기타를'], hints: ['can play', 'the guitar'], answer: 'He can play the guitar.' },
  { id: 56, level: 1, korean: '우리는 내일 소풍을 가요.', wordOrder: ['우리는 가요', '소풍을', '내일'], hints: ['go on', 'a picnic', 'tomorrow'], answer: 'We go on a picnic tomorrow.' },
  { id: 57, level: 1, korean: '나는 방금 점심을 먹었어요.', wordOrder: ['나는 방금 먹었어요', '점심을'], hints: ['just had', 'lunch'], answer: 'I just had lunch.' },
  { id: 58, level: 1, korean: '그녀는 꽃을 좋아해요.', wordOrder: ['그녀는 좋아해요', '꽃을'], hints: ['like', 'flowers'], answer: 'She likes flowers.' },
  { id: 59, level: 1, korean: '우리 집은 학교 근처에 있어요.', wordOrder: ['우리 집은 있어요', '학교 근처에'], hints: ['house', 'near the school'], answer: 'My house is near the school.' },
  { id: 60, level: 1, korean: '그는 아버지를 많이 닮았어요.', wordOrder: ['그는 닮았어요', '그의 아버지를', '많이'], hints: ['look like', 'father', 'a lot'], answer: 'He looks a lot like his father.' },
  { id: 61, level: 1, korean: '나는 요즘 바빠요.', wordOrder: ['나는 바빠요', '요즘'], hints: ['busy', 'these days'], answer: 'I am busy these days.' },
  { id: 62, level: 1, korean: '그녀는 항상 웃어요.', wordOrder: ['그녀는 항상 웃어요'], hints: ['always', 'smile'], answer: 'She always smiles.' },
  { id: 63, level: 1, korean: '우리는 같은 반이에요.', wordOrder: ['우리는 있어요', '같은 반에'], hints: ['in', 'the same class'], answer: 'We are in the same class.' },
  { id: 64, level: 1, korean: '그는 키가 아주 커요.', wordOrder: ['그는', '아주 키가 커요'], hints: ['very', 'tall'], answer: 'He is very tall.' },
  { id: 65, level: 1, korean: '나는 딸기 아이스크림을 좋아해요.', wordOrder: ['나는 좋아해요', '딸기 아이스크림을'], hints: ['like', 'strawberry ice cream'], answer: 'I like strawberry ice cream.' },
  { id: 66, level: 1, korean: '그녀는 오늘 일찍 왔어요.', wordOrder: ['그녀는 왔어요', '일찍', '오늘'], hints: ['came', 'early', 'today'], answer: 'She came early today.' },
  { id: 67, level: 1, korean: '우리는 주말마다 등산을 해요.', wordOrder: ['우리는 등산해요', '매 주말'], hints: ['hike', 'every weekend'], answer: 'We hike every weekend.' },
  { id: 68, level: 1, korean: '그는 은행에서 일해요.', wordOrder: ['그는 일해요', '은행에서'], hints: ['work', 'at a bank'], answer: 'He works at a bank.' },
  { id: 69, level: 1, korean: '나는 오렌지 주스를 주문했어요.', wordOrder: ['나는 주문했어요', '오렌지 주스를'], hints: ['ordered', 'orange juice'], answer: 'I ordered orange juice.' },
  { id: 70, level: 1, korean: '그녀는 그 소식을 듣고 기뻐했어요.', wordOrder: ['그녀는 기뻐했어요', '그 소식을 듣고'], hints: ['was happy', 'to hear the news'], answer: 'She was happy to hear the news.' },

  // ===== Level 2: 중급 (id 71-140) - 부사구, 전치사구, to부정사, 접속사 =====
  { id: 71, level: 2, korean: '그는 건강을 유지하려고 매일 걸어서 출근해요.', wordOrder: ['그는 걸어요', '회사까지', '매일', '건강을 유지하려고'], hints: ['walk', 'to work', 'stay healthy'], answer: 'He walks to work every day to stay healthy.' },
  { id: 72, level: 2, korean: '나는 비가 올 때 보통 집에서 책을 읽어요.', wordOrder: ['나는 보통 읽어요', '책을', '집에서', '비가 올 때'], hints: ['usually', 'read', 'when it rains'], answer: 'I usually read books at home when it rains.' },
  { id: 73, level: 2, korean: '우리 엄마는 저녁마다 맛있는 음식을 만들어 주세요.', wordOrder: ['우리 엄마는 만들어요', '맛있는 음식을', '우리에게', '매일 저녁'], hints: ['make', 'delicious food', 'every evening'], answer: 'My mom makes delicious food for us every evening.' },
  { id: 74, level: 2, korean: '그녀는 시험에 합격하기 위해 열심히 공부했어요.', wordOrder: ['그녀는 공부했어요', '열심히', '합격하기 위해', '시험에'], hints: ['studied', 'hard', 'pass the exam'], answer: 'She studied hard to pass the exam.' },
  { id: 75, level: 2, korean: '나는 지난 여름에 가족과 함께 제주도에 갔어요.', wordOrder: ['나는 갔어요', '제주도에', '가족과 함께', '지난 여름에'], hints: ['went', 'Jeju Island', 'with my family'], answer: 'I went to Jeju Island with my family last summer.' },
  { id: 76, level: 2, korean: '그는 피곤해서 일찍 잠자리에 들었어요.', wordOrder: ['그는 잠자리에 들었어요', '일찍', '왜냐하면', '그는 피곤했으니까'], hints: ['went to bed', 'early', 'because', 'tired'], answer: 'He went to bed early because he was tired.' },
  { id: 77, level: 2, korean: '나는 새로운 것을 배우는 것을 즐겨요.', wordOrder: ['나는 즐겨요', '배우는 것을', '새로운 것을'], hints: ['enjoy', 'learning', 'new things'], answer: 'I enjoy learning new things.' },
  { id: 78, level: 2, korean: '그녀는 외국에서 공부하고 싶어해요.', wordOrder: ['그녀는 원해요', '공부하기를', '외국에서'], hints: ['want', 'to study', 'abroad'], answer: 'She wants to study abroad.' },
  { id: 79, level: 2, korean: '우리는 날씨가 좋으면 밖에서 놀아요.', wordOrder: ['우리는 놀아요', '밖에서', '날씨가 좋으면'], hints: ['play', 'outside', 'if the weather is nice'], answer: 'We play outside if the weather is nice.' },
  { id: 80, level: 2, korean: '그는 아침을 먹기 전에 운동을 해요.', wordOrder: ['그는 운동해요', '먹기 전에', '아침을'], hints: ['exercise', 'before', 'breakfast'], answer: 'He exercises before eating breakfast.' },
  { id: 81, level: 2, korean: '나는 음악을 들으면서 공부해요.', wordOrder: ['나는 공부해요', '들으면서', '음악을'], hints: ['study', 'while listening to', 'music'], answer: 'I study while listening to music.' },
  { id: 82, level: 2, korean: '그녀는 매일 30분씩 영어 뉴스를 들어요.', wordOrder: ['그녀는 들어요', '영어 뉴스를', '30분 동안', '매일'], hints: ['listen to', 'English news', 'for 30 minutes'], answer: 'She listens to English news for 30 minutes every day.' },
  { id: 83, level: 2, korean: '우리는 졸업한 후에 여행을 갈 계획이에요.', wordOrder: ['우리는 계획해요', '여행을 가기를', '졸업한 후에'], hints: ['plan', 'to travel', 'after graduating'], answer: 'We plan to travel after graduating.' },
  { id: 84, level: 2, korean: '그는 돈을 모으려고 아르바이트를 해요.', wordOrder: ['그는 아르바이트를 해요', '돈을 모으려고'], hints: ['work part-time', 'to save money'], answer: 'He works part-time to save money.' },
  { id: 85, level: 2, korean: '나는 그 식당이 맛있다고 들었어요.', wordOrder: ['나는 들었어요', '그 식당이', '맛있다고'], hints: ['heard', 'the restaurant', 'is good'], answer: 'I heard that the restaurant is good.' },
  { id: 86, level: 2, korean: '그녀는 운동을 시작한 후에 건강해졌어요.', wordOrder: ['그녀는 건강해졌어요', '시작한 후에', '운동을'], hints: ['became healthier', 'after', 'started exercising'], answer: 'She became healthier after she started exercising.' },
  { id: 87, level: 2, korean: '우리는 비가 와서 소풍을 취소했어요.', wordOrder: ['우리는 취소했어요', '소풍을', '비가 와서'], hints: ['canceled', 'the picnic', 'because of the rain'], answer: 'We canceled the picnic because of the rain.' },
  { id: 88, level: 2, korean: '나는 커피보다 차를 더 좋아해요.', wordOrder: ['나는 더 좋아해요', '차를', '커피보다'], hints: ['prefer', 'tea', 'to coffee'], answer: 'I prefer tea to coffee.' },
  { id: 89, level: 2, korean: '그는 나보다 세 살 더 많아요.', wordOrder: ['그는', '세 살 더 나이가 많아요', '나보다'], hints: ['three years', 'older', 'than me'], answer: 'He is three years older than me.' },
  { id: 90, level: 2, korean: '그녀는 요리하는 것을 배우고 있어요.', wordOrder: ['그녀는 배우고 있어요', '요리하는 것을'], hints: ['is learning', 'to cook'], answer: 'She is learning to cook.' },
  { id: 91, level: 2, korean: '나는 그 영화가 재미없다고 생각해요.', wordOrder: ['나는 생각해요', '그 영화가', '재미없다고'], hints: ['think', 'the movie', 'is boring'], answer: 'I think the movie is boring.' },
  { id: 92, level: 2, korean: '우리는 서로 도와가며 프로젝트를 완성했어요.', wordOrder: ['우리는 완성했어요', '프로젝트를', '서로 도와가며'], hints: ['completed', 'the project', 'by helping each other'], answer: 'We completed the project by helping each other.' },
  { id: 93, level: 2, korean: '그는 집에 올 때 빵을 사 왔어요.', wordOrder: ['그는 사 왔어요', '빵을', '집에 올 때'], hints: ['bought', 'bread', 'on his way home'], answer: 'He bought bread on his way home.' },
  { id: 94, level: 2, korean: '나는 일본에 가 본 적이 있어요.', wordOrder: ['나는 가 본 적이 있어요', '일본에'], hints: ['have been', 'to Japan'], answer: 'I have been to Japan.' },
  { id: 95, level: 2, korean: '그녀는 5년 동안 피아노를 배웠어요.', wordOrder: ['그녀는 배웠어요', '피아노를', '5년 동안'], hints: ['learned', 'piano', 'for five years'], answer: 'She learned piano for five years.' },
  { id: 96, level: 2, korean: '우리는 그 문제에 대해 오래 이야기했어요.', wordOrder: ['우리는 이야기했어요', '그 문제에 대해', '오랫동안'], hints: ['talked', 'about the problem', 'for a long time'], answer: 'We talked about the problem for a long time.' },
  { id: 97, level: 2, korean: '그는 늦지 않으려고 택시를 탔어요.', wordOrder: ['그는 탔어요', '택시를', '늦지 않으려고'], hints: ['took', 'a taxi', 'in order not to be late'], answer: 'He took a taxi in order not to be late.' },
  { id: 98, level: 2, korean: '나는 어렸을 때 수영을 배웠어요.', wordOrder: ['나는 배웠어요', '수영을', '어렸을 때'], hints: ['learned', 'to swim', 'when I was young'], answer: 'I learned to swim when I was young.' },
  { id: 99, level: 2, korean: '그녀는 회의가 끝나자마자 전화했어요.', wordOrder: ['그녀는 전화했어요', '끝나자마자', '회의가'], hints: ['called', 'as soon as', 'the meeting ended'], answer: 'She called as soon as the meeting ended.' },
  { id: 100, level: 2, korean: '우리는 더 큰 집으로 이사할 거예요.', wordOrder: ['우리는 이사할 거예요', '더 큰 집으로'], hints: ['will move', 'to a bigger house'], answer: 'We will move to a bigger house.' },
  { id: 101, level: 2, korean: '그는 아플 때도 학교에 가요.', wordOrder: ['그는 가요', '학교에', '아플 때도'], hints: ['go', 'to school', 'even when he is sick'], answer: 'He goes to school even when he is sick.' },
  { id: 102, level: 2, korean: '나는 매달 용돈을 저축해요.', wordOrder: ['나는 저축해요', '용돈을', '매달'], hints: ['save', 'allowance', 'every month'], answer: 'I save my allowance every month.' },
  { id: 103, level: 2, korean: '그녀는 결과에 매우 만족했어요.', wordOrder: ['그녀는 매우 만족했어요', '결과에'], hints: ['was very satisfied', 'with the result'], answer: 'She was very satisfied with the result.' },
  { id: 104, level: 2, korean: '우리는 점심을 먹은 후에 산책했어요.', wordOrder: ['우리는 산책했어요', '점심을 먹은 후에'], hints: ['took a walk', 'after having lunch'], answer: 'We took a walk after having lunch.' },
  { id: 105, level: 2, korean: '그는 영어뿐만 아니라 일본어도 할 수 있어요.', wordOrder: ['그는 말할 수 있어요', '영어뿐만 아니라', '일본어도'], hints: ['can speak', 'not only English', 'but also Japanese'], answer: 'He can speak not only English but also Japanese.' },
  { id: 106, level: 2, korean: '나는 너무 많이 먹어서 배가 아파요.', wordOrder: ['나의 배가 아파요', '왜냐하면', '나는 너무 많이 먹었으니까'], hints: ['stomach hurts', 'because', 'ate too much'], answer: 'My stomach hurts because I ate too much.' },
  { id: 107, level: 2, korean: '그녀는 졸업하면 유럽에 갈 거예요.', wordOrder: ['그녀는 갈 거예요', '유럽에', '졸업하면'], hints: ['will go', 'to Europe', 'when she graduates'], answer: 'She will go to Europe when she graduates.' },
  { id: 108, level: 2, korean: '우리는 약속 시간에 맞추려고 서둘렀어요.', wordOrder: ['우리는 서둘렀어요', '맞추려고', '약속 시간에'], hints: ['hurried', 'to make it', 'on time'], answer: 'We hurried to make it on time.' },
  { id: 109, level: 2, korean: '그는 다른 사람들을 돕는 것을 좋아해요.', wordOrder: ['그는 좋아해요', '돕는 것을', '다른 사람들을'], hints: ['like', 'helping', 'other people'], answer: 'He likes helping other people.' },
  { id: 110, level: 2, korean: '나는 집에 도착하자마자 손을 씻었어요.', wordOrder: ['나는 씻었어요', '내 손을', '도착하자마자', '집에'], hints: ['washed', 'my hands', 'as soon as I arrived'], answer: 'I washed my hands as soon as I arrived home.' },
  { id: 111, level: 2, korean: '그녀는 다이어트를 하면서 운동도 해요.', wordOrder: ['그녀는 운동도 해요', '다이어트를 하면서'], hints: ['also exercises', 'while on a diet'], answer: 'She also exercises while on a diet.' },
  { id: 112, level: 2, korean: '우리는 그 소식을 듣고 매우 놀랐어요.', wordOrder: ['우리는 매우 놀랐어요', '들었을 때', '그 소식을'], hints: ['were very surprised', 'when we heard', 'the news'], answer: 'We were very surprised when we heard the news.' },
  { id: 113, level: 2, korean: '그는 매일 한 시간씩 독서를 해요.', wordOrder: ['그는 독서해요', '한 시간 동안', '매일'], hints: ['read', 'for an hour', 'every day'], answer: 'He reads for an hour every day.' },
  { id: 114, level: 2, korean: '나는 실수를 해서 다시 해야 했어요.', wordOrder: ['나는 해야 했어요', '다시', '왜냐하면', '실수를 해서'], hints: ['had to do it', 'again', 'because', 'made a mistake'], answer: 'I had to do it again because I made a mistake.' },
  { id: 115, level: 2, korean: '그녀는 친구에게 선물을 보냈어요.', wordOrder: ['그녀는 보냈어요', '선물을', '그녀의 친구에게'], hints: ['sent', 'a gift', 'to her friend'], answer: 'She sent a gift to her friend.' },
  { id: 116, level: 2, korean: '우리는 서울에서 가장 유명한 식당에 갔어요.', wordOrder: ['우리는 갔어요', '가장 유명한 식당에', '서울에서'], hints: ['went', 'the most famous restaurant', 'in Seoul'], answer: 'We went to the most famous restaurant in Seoul.' },
  { id: 117, level: 2, korean: '그는 대학교를 졸업한 후에 취직했어요.', wordOrder: ['그는 취직했어요', '졸업한 후에', '대학교를'], hints: ['got a job', 'after graduating', 'from college'], answer: 'He got a job after graduating from college.' },
  { id: 118, level: 2, korean: '나는 내일 비가 올 것 같아요.', wordOrder: ['나는 생각해요', '비가 올 것이라고', '내일'], hints: ['think', 'it will rain', 'tomorrow'], answer: 'I think it will rain tomorrow.' },
  { id: 119, level: 2, korean: '그녀는 혼자서 해외여행을 했어요.', wordOrder: ['그녀는 여행했어요', '해외로', '혼자서'], hints: ['traveled', 'abroad', 'by herself'], answer: 'She traveled abroad by herself.' },
  { id: 120, level: 2, korean: '우리는 경기에서 이겨서 정말 기뻤어요.', wordOrder: ['우리는 정말 기뻤어요', '왜냐하면', '이겼으니까', '경기에서'], hints: ['were really happy', 'because', 'won the game'], answer: 'We were really happy because we won the game.' },
  { id: 121, level: 2, korean: '그는 아무것도 먹지 않고 학교에 갔어요.', wordOrder: ['그는 갔어요', '학교에', '먹지 않고', '아무것도'], hints: ['went', 'to school', 'without eating', 'anything'], answer: 'He went to school without eating anything.' },
  { id: 122, level: 2, korean: '나는 서점에서 재미있는 책을 발견했어요.', wordOrder: ['나는 발견했어요', '재미있는 책을', '서점에서'], hints: ['found', 'an interesting book', 'at the bookstore'], answer: 'I found an interesting book at the bookstore.' },
  { id: 123, level: 2, korean: '그녀는 다른 도시로 이사한 후에 연락이 끊겼어요.', wordOrder: ['우리는 연락이 끊겼어요', '그녀가 이사한 후에', '다른 도시로'], hints: ['lost touch', 'after she moved', 'to another city'], answer: 'We lost touch after she moved to another city.' },
  { id: 124, level: 2, korean: '우리는 계획을 세운 후에 바로 실행했어요.', wordOrder: ['우리는 실행했어요', '바로', '계획을 세운 후에'], hints: ['carried it out', 'right away', 'after making a plan'], answer: 'We carried it out right away after making a plan.' },
  { id: 125, level: 2, korean: '그는 월급을 받으면 항상 부모님께 용돈을 드려요.', wordOrder: ['그는 항상 드려요', '부모님께 용돈을', '월급을 받으면'], hints: ['always gives', 'allowance to his parents', 'when he gets paid'], answer: 'He always gives his parents allowance when he gets paid.' },
  { id: 126, level: 2, korean: '나는 요즘 살이 쪄서 운동을 시작했어요.', wordOrder: ['나는 시작했어요', '운동을', '왜냐하면', '살이 쪘으니까 요즘'], hints: ['started', 'exercising', 'because', 'gained weight'], answer: 'I started exercising because I gained weight recently.' },
  { id: 127, level: 2, korean: '그녀는 영어를 배우기 위해 미국에 갔어요.', wordOrder: ['그녀는 갔어요', '미국에', '배우기 위해', '영어를'], hints: ['went', 'to America', 'to learn', 'English'], answer: 'She went to America to learn English.' },
  { id: 128, level: 2, korean: '우리는 10년 전에 이 동네로 이사 왔어요.', wordOrder: ['우리는 이사 왔어요', '이 동네로', '10년 전에'], hints: ['moved', 'to this neighborhood', 'ten years ago'], answer: 'We moved to this neighborhood ten years ago.' },
  { id: 129, level: 2, korean: '그는 회사에 늦어서 택시를 탔어요.', wordOrder: ['그는 탔어요', '택시를', '왜냐하면', '회사에 늦었으니까'], hints: ['took', 'a taxi', 'because', 'was late for work'], answer: 'He took a taxi because he was late for work.' },
  { id: 130, level: 2, korean: '나는 친구를 만나려고 강남에 갔어요.', wordOrder: ['나는 갔어요', '강남에', '만나려고', '친구를'], hints: ['went', 'to Gangnam', 'to meet', 'my friend'], answer: 'I went to Gangnam to meet my friend.' },
  { id: 131, level: 2, korean: '그녀는 자기 전에 항상 일기를 써요.', wordOrder: ['그녀는 항상 써요', '일기를', '자기 전에'], hints: ['always writes', 'a diary', 'before going to bed'], answer: 'She always writes a diary before going to bed.' },
  { id: 132, level: 2, korean: '우리는 다음 달에 결혼식에 초대받았어요.', wordOrder: ['우리는 초대받았어요', '결혼식에', '다음 달에'], hints: ['were invited', 'to a wedding', 'next month'], answer: 'We were invited to a wedding next month.' },
  { id: 133, level: 2, korean: '그는 한국에 온 지 3년이 되었어요.', wordOrder: ['그는 있었어요', '한국에', '3년 동안'], hints: ['has been', 'in Korea', 'for three years'], answer: 'He has been in Korea for three years.' },
  { id: 134, level: 2, korean: '나는 그 노래를 들으면 고향이 생각나요.', wordOrder: ['나는 생각나요', '고향이', '들으면', '그 노래를'], hints: ['think of', 'my hometown', 'when I hear', 'that song'], answer: 'I think of my hometown when I hear that song.' },
  { id: 135, level: 2, korean: '그녀는 시간이 있을 때 자원봉사를 해요.', wordOrder: ['그녀는 자원봉사해요', '시간이 있을 때'], hints: ['volunteer', 'when she has time'], answer: 'She volunteers when she has time.' },
  { id: 136, level: 2, korean: '우리는 할머니 댁에 명절마다 가요.', wordOrder: ['우리는 가요', '할머니 댁에', '매 명절마다'], hints: ['visit', "grandmother's house", 'every holiday'], answer: "We visit our grandmother's house every holiday." },
  { id: 137, level: 2, korean: '그는 회의 중에 좋은 아이디어를 떠올렸어요.', wordOrder: ['그는 떠올렸어요', '좋은 아이디어를', '회의 중에'], hints: ['came up with', 'a good idea', 'during the meeting'], answer: 'He came up with a good idea during the meeting.' },
  { id: 138, level: 2, korean: '나는 이 책을 다 읽으면 너에게 빌려줄게.', wordOrder: ['나는 빌려줄게', '너에게', '이 책을', '다 읽으면'], hints: ['will lend', 'this book', 'when I finish reading'], answer: 'I will lend you this book when I finish reading it.' },
  { id: 139, level: 2, korean: '그녀는 노력한 만큼 좋은 결과를 얻었어요.', wordOrder: ['그녀는 얻었어요', '좋은 결과를', '노력한 만큼'], hints: ['got', 'good results', 'as much as she tried'], answer: 'She got good results as much as she tried.' },
  { id: 140, level: 2, korean: '우리는 서로의 문화를 이해하려고 노력해요.', wordOrder: ['우리는 노력해요', '이해하려고', '서로의 문화를'], hints: ['try', 'to understand', "each other's culture"], answer: "We try to understand each other's culture." },

  // ===== Level 3: 고급 (id 141-200) - 분사구문, 관계절, 가정법, 복합 시제 =====
  { id: 141, level: 3, korean: '실패에 동기를 받아, 그는 훨씬 더 열심히 일했어요.', wordOrder: ['동기를 부여받아', '그의 실패들에', '그는 일했어요', '훨씬 더 열심히'], hints: ['motivated', 'failures', 'even harder'], answer: 'Motivated by his failures, he worked even harder.' },
  { id: 142, level: 3, korean: '비록 날씨가 나빴지만, 우리는 등산을 계속했어요.', wordOrder: ['비록', '날씨가 나빴지만', '우리는 계속했어요', '등산을'], hints: ['although', 'the weather was bad', 'continued hiking'], answer: 'Although the weather was bad, we continued hiking.' },
  { id: 143, level: 3, korean: '그가 말한 것이 사실이라면, 우리는 계획을 바꿔야 해요.', wordOrder: ['만약', '그가 말한 것이', '사실이라면', '우리는 바꿔야 해요', '우리의 계획을'], hints: ['if', 'what he said', 'is true', 'change our plan'], answer: 'If what he said is true, we need to change our plan.' },
  { id: 144, level: 3, korean: '나는 그 영화를 보기 전에 원작 소설을 먼저 읽고 싶어요.', wordOrder: ['나는 읽고 싶어요', '원작 소설을', '먼저', '보기 전에', '그 영화를'], hints: ['want to read', 'the original novel', 'before watching'], answer: 'I want to read the original novel first before watching the movie.' },
  { id: 145, level: 3, korean: '내가 어렸을 때 살던 동네에는 큰 나무가 있는 공원이 있었어요.', wordOrder: ['있었어요', '공원이', '큰 나무가 있는', '동네에', '내가 어렸을 때 살던'], hints: ['there was', 'a park', 'with big trees', 'the neighborhood', 'where I lived'], answer: 'There was a park with big trees in the neighborhood where I lived as a child.' },
  { id: 146, level: 3, korean: '모든 준비를 마친 후, 그들은 새로운 사업을 시작했어요.', wordOrder: ['마친 후', '모든 준비를', '그들은 시작했어요', '새로운 사업을'], hints: ['having completed', 'all the preparations', 'launched', 'a new business'], answer: 'Having completed all the preparations, they launched a new business.' },
  { id: 147, level: 3, korean: '그녀가 추천해 준 책은 정말 감동적이었어요.', wordOrder: ['그 책은', '그녀가 추천해 준', '정말 감동적이었어요'], hints: ['the book', 'that she recommended', 'truly moving'], answer: 'The book that she recommended was truly moving.' },
  { id: 148, level: 3, korean: '만약 내가 시간이 더 있었다면, 그 프로젝트를 더 잘 끝냈을 거예요.', wordOrder: ['만약', '내가 더 시간이 있었다면', '나는 끝냈을 거예요', '그 프로젝트를', '더 잘'], hints: ['if I had had', 'more time', 'would have finished', 'better'], answer: 'If I had had more time, I would have finished the project better.' },
  { id: 149, level: 3, korean: '많은 사람들에게 사랑받는 그 가수는 다음 주에 콘서트를 해요.', wordOrder: ['그 가수는', '사랑받는', '많은 사람들에게', '콘서트를 해요', '다음 주에'], hints: ['the singer', 'loved', 'by many people', 'concert', 'next week'], answer: 'The singer who is loved by many people is having a concert next week.' },
  { id: 150, level: 3, korean: '아무리 바빠도, 그는 항상 가족과 저녁을 먹으려고 노력해요.', wordOrder: ['아무리 바빠도', '그는 항상 노력해요', '먹으려고', '저녁을', '가족과'], hints: ['no matter how busy', 'always tries', 'to have dinner', 'with his family'], answer: 'No matter how busy he is, he always tries to have dinner with his family.' },
  { id: 151, level: 3, korean: '그 문제를 해결하기 위해서는 새로운 접근 방식이 필요해요.', wordOrder: ['새로운 접근 방식이', '필요해요', '해결하기 위해서는', '그 문제를'], hints: ['a new approach', 'is needed', 'in order to solve', 'the problem'], answer: 'A new approach is needed in order to solve the problem.' },
  { id: 152, level: 3, korean: '길을 걷다가 오래전에 헤어진 친구를 우연히 만났어요.', wordOrder: ['나는 우연히 만났어요', '친구를', '오래전에 헤어진', '걷다가', '길을'], hints: ['ran into', 'a friend', 'I had lost touch with', 'while walking'], answer: 'While walking down the street, I ran into a friend I had lost touch with long ago.' },
  { id: 153, level: 3, korean: '그녀는 마치 아무 일도 없었던 것처럼 행동했어요.', wordOrder: ['그녀는 행동했어요', '마치', '아무 일도', '없었던 것처럼'], hints: ['acted', 'as if', 'nothing', 'had happened'], answer: 'She acted as if nothing had happened.' },
  { id: 154, level: 3, korean: '경험이 풍부한 그 의사는 환자들에게 인기가 많아요.', wordOrder: ['그 의사는', '경험이 풍부한', '인기가 많아요', '환자들에게'], hints: ['the doctor', 'experienced', 'popular', 'among patients'], answer: 'The experienced doctor is popular among patients.' },
  { id: 155, level: 3, korean: '노력 없이는 아무것도 이룰 수 없어요.', wordOrder: ['아무것도', '이룰 수 없어요', '없이는', '노력'], hints: ['nothing', 'can be achieved', 'without', 'effort'], answer: 'Nothing can be achieved without effort.' },
  { id: 156, level: 3, korean: '그가 떠난 후에야 나는 그의 소중함을 깨달았어요.', wordOrder: ['그가 떠난 후에야', '나는 깨달았어요', '그가 얼마나 소중한지'], hints: ['only after he left', 'did I realize', 'how precious he was'], answer: 'Only after he left did I realize how precious he was.' },
  { id: 157, level: 3, korean: '이 도시에서 태어나고 자란 그녀는 모든 골목을 알고 있어요.', wordOrder: ['태어나고 자란', '이 도시에서', '그녀는 알고 있어요', '모든 골목을'], hints: ['born and raised', 'in this city', 'knows', 'every alley'], answer: 'Born and raised in this city, she knows every alley.' },
  { id: 158, level: 3, korean: '네가 없었다면 나는 그 일을 해내지 못했을 거예요.', wordOrder: ['네가 없었다면', '나는 못했을 거예요', '해내지', '그 일을'], hints: ['without you', 'could not have', 'accomplished', 'the task'], answer: 'Without you, I could not have accomplished the task.' },
  { id: 159, level: 3, korean: '세계 여러 나라에서 온 학생들이 그 대학교에서 공부해요.', wordOrder: ['학생들이', '여러 나라에서 온', '세계', '공부해요', '그 대학교에서'], hints: ['students', 'from various countries', 'around the world', 'study'], answer: 'Students from various countries around the world study at that university.' },
  { id: 160, level: 3, korean: '열심히 일한 덕분에 그녀는 승진했어요.', wordOrder: ['덕분에', '열심히 일한', '그녀는 승진했어요'], hints: ['thanks to', 'her hard work', 'was promoted'], answer: 'Thanks to her hard work, she was promoted.' },
  { id: 161, level: 3, korean: '그가 제안한 방법이 가장 효율적인 것으로 판명되었어요.', wordOrder: ['그 방법이', '그가 제안한', '판명되었어요', '가장 효율적인 것으로'], hints: ['the method', 'he suggested', 'turned out', 'to be the most efficient'], answer: 'The method he suggested turned out to be the most efficient.' },
  { id: 162, level: 3, korean: '아이들의 웃음소리가 들리는 놀이터는 항상 활기차요.', wordOrder: ['놀이터는', '아이들의 웃음소리가 들리는', '항상 활기차요'], hints: ['the playground', "where children's laughter can be heard", 'always lively'], answer: "The playground where children's laughter can be heard is always lively." },
  { id: 163, level: 3, korean: '그렇게 어려운 상황에서도 그는 포기하지 않았어요.', wordOrder: ['그렇게 어려운 상황에서도', '그는 포기하지 않았어요'], hints: ['even in such a difficult situation', 'did not give up'], answer: 'Even in such a difficult situation, he did not give up.' },
  { id: 164, level: 3, korean: '내가 가장 존경하는 사람은 우리 할아버지예요.', wordOrder: ['그 사람은', '내가 가장 존경하는', '우리 할아버지예요'], hints: ['the person', 'I respect the most', 'my grandfather'], answer: 'The person I respect the most is my grandfather.' },
  { id: 165, level: 3, korean: '모든 것을 고려했을 때, 이것이 최선의 선택이에요.', wordOrder: ['모든 것을 고려했을 때', '이것이', '최선의 선택이에요'], hints: ['all things considered', 'this is', 'the best choice'], answer: 'All things considered, this is the best choice.' },
  { id: 166, level: 3, korean: '일찍 출발했더라면 교통 체증을 피할 수 있었을 거예요.', wordOrder: ['만약 우리가 출발했더라면', '더 일찍', '피할 수 있었을 거예요', '교통 체증을'], hints: ['if we had left', 'earlier', 'could have avoided', 'the traffic jam'], answer: 'If we had left earlier, we could have avoided the traffic jam.' },
  { id: 167, level: 3, korean: '그녀는 어디를 가든지 사람들의 관심을 끌어요.', wordOrder: ['그녀는 끌어요', '사람들의 관심을', '어디를 가든지'], hints: ['attract', "people's attention", 'wherever she goes'], answer: "She attracts people's attention wherever she goes." },
  { id: 168, level: 3, korean: '우리가 겪고 있는 문제는 쉽게 해결될 것 같지 않아요.', wordOrder: ['그 문제는', '우리가 겪고 있는', '것 같지 않아요', '쉽게 해결될'], hints: ['the problem', 'we are facing', 'is unlikely', 'to be easily solved'], answer: 'The problem we are facing is unlikely to be easily solved.' },
  { id: 169, level: 3, korean: '역사에서 배우지 않는 사람은 같은 실수를 반복해요.', wordOrder: ['사람들은', '배우지 않는', '역사에서', '반복해요', '같은 실수를'], hints: ['those who', 'do not learn', 'from history', 'repeat', 'the same mistakes'], answer: 'Those who do not learn from history repeat the same mistakes.' },
  { id: 170, level: 3, korean: '지구 온난화가 계속된다면 많은 동물들이 멸종할 수도 있어요.', wordOrder: ['만약', '지구 온난화가 계속된다면', '많은 동물들이', '멸종할 수도 있어요'], hints: ['if', 'global warming continues', 'many animals', 'could become extinct'], answer: 'If global warming continues, many animals could become extinct.' },
  { id: 171, level: 3, korean: '문을 열자 시원한 바람이 불어왔어요.', wordOrder: ['내가 열자', '문을', '시원한 바람이', '불어왔어요'], hints: ['when I opened', 'the door', 'a cool breeze', 'blew in'], answer: 'When I opened the door, a cool breeze blew in.' },
  { id: 172, level: 3, korean: '솔직히 말해서, 나는 그의 의견에 동의하지 않아요.', wordOrder: ['솔직히 말해서', '나는 동의하지 않아요', '그의 의견에'], hints: ['to be honest', 'do not agree', 'with his opinion'], answer: 'To be honest, I do not agree with his opinion.' },
  { id: 173, level: 3, korean: '수년간 연습한 결과, 그녀는 훌륭한 바이올리니스트가 되었어요.', wordOrder: ['연습한 결과', '수년간', '그녀는 되었어요', '훌륭한 바이올리니스트가'], hints: ['as a result of practicing', 'for years', 'became', 'an excellent violinist'], answer: 'As a result of practicing for years, she became an excellent violinist.' },
  { id: 174, level: 3, korean: '내가 존경하는 선생님은 항상 학생들을 격려하세요.', wordOrder: ['선생님은', '내가 존경하는', '항상 격려하세요', '학생들을'], hints: ['the teacher', 'I admire', 'always encourages', 'students'], answer: 'The teacher I admire always encourages students.' },
  { id: 175, level: 3, korean: '환경을 보호하는 것은 우리 모두의 책임이에요.', wordOrder: ['보호하는 것은', '환경을', '우리 모두의 책임이에요'], hints: ['protecting', 'the environment', "everyone's responsibility"], answer: "Protecting the environment is everyone's responsibility." },
  { id: 176, level: 3, korean: '그 회사에서 일하는 동안 그는 많은 것을 배웠어요.', wordOrder: ['일하는 동안', '그 회사에서', '그는 배웠어요', '많은 것을'], hints: ['while working', 'at that company', 'learned', 'a lot'], answer: 'While working at that company, he learned a lot.' },
  { id: 177, level: 3, korean: '어떤 어려움이 닥치더라도 우리는 함께 극복할 수 있어요.', wordOrder: ['어떤 어려움이 닥치더라도', '우리는 극복할 수 있어요', '함께'], hints: ['whatever difficulties come', 'we can overcome', 'together'], answer: 'Whatever difficulties come, we can overcome them together.' },
  { id: 178, level: 3, korean: '오랫동안 기다려 온 그 순간이 드디어 왔어요.', wordOrder: ['그 순간이', '오랫동안 기다려 온', '드디어 왔어요'], hints: ['the moment', 'we had been waiting for', 'finally came'], answer: 'The moment we had been waiting for finally came.' },
  { id: 179, level: 3, korean: '그녀의 도움이 아니었다면 우리는 마감일을 맞추지 못했을 거예요.', wordOrder: ['그녀의 도움이 아니었다면', '우리는 못했을 거예요', '맞추지', '마감일을'], hints: ['without her help', 'could not have', 'met', 'the deadline'], answer: 'Without her help, we could not have met the deadline.' },
  { id: 180, level: 3, korean: '그 나라에서 보낸 1년은 내 인생을 완전히 바꿨어요.', wordOrder: ['1년은', '내가 보낸', '그 나라에서', '완전히 바꿨어요', '내 인생을'], hints: ['the year', 'I spent', 'in that country', 'completely changed', 'my life'], answer: 'The year I spent in that country completely changed my life.' },
  { id: 181, level: 3, korean: '아무리 노력해도 완벽할 수는 없어요.', wordOrder: ['아무리 노력해도', '아무도 될 수 없어요', '완벽하게'], hints: ['no matter how hard you try', 'nobody can be', 'perfect'], answer: 'No matter how hard you try, nobody can be perfect.' },
  { id: 182, level: 3, korean: '내가 어렸을 때 읽었던 책들이 지금의 나를 만들었어요.', wordOrder: ['책들이', '내가 읽었던', '어렸을 때', '만들었어요', '지금의 나를'], hints: ['the books', 'I read', 'when I was young', 'shaped', 'who I am today'], answer: 'The books I read when I was young shaped who I am today.' },
  { id: 183, level: 3, korean: '눈이 많이 쌓여서 학교가 문을 닫았어요.', wordOrder: ['학교가 문을 닫았어요', '왜냐하면', '눈이 많이 쌓였으니까'], hints: ['the school was closed', 'due to', 'heavy snow'], answer: 'The school was closed due to heavy snow.' },
  { id: 184, level: 3, korean: '그는 다른 사람들이 생각하는 것에 신경 쓰지 않아요.', wordOrder: ['그는 신경 쓰지 않아요', '다른 사람들이 생각하는 것에'], hints: ['does not care', 'about what other people think'], answer: 'He does not care about what other people think.' },
  { id: 185, level: 3, korean: '좋은 책을 읽는 것은 현명한 사람과 대화하는 것과 같아요.', wordOrder: ['읽는 것은', '좋은 책을', '같아요', '대화하는 것과', '현명한 사람과'], hints: ['reading', 'a good book', 'is like', 'having a conversation', 'with a wise person'], answer: 'Reading a good book is like having a conversation with a wise person.' },
  { id: 186, level: 3, korean: '그녀는 자신이 원하는 것이 무엇인지 정확히 알고 있어요.', wordOrder: ['그녀는 정확히 알고 있어요', '무엇인지', '자신이 원하는 것이'], hints: ['knows exactly', 'what', 'she wants'], answer: 'She knows exactly what she wants.' },
  { id: 187, level: 3, korean: '기회가 왔을 때 그것을 잡지 않으면 후회하게 될 거예요.', wordOrder: ['만약 잡지 않으면', '기회를', '그것이 왔을 때', '후회하게 될 거예요'], hints: ['if you do not seize', 'the opportunity', 'when it comes', 'you will regret it'], answer: 'If you do not seize the opportunity when it comes, you will regret it.' },
  { id: 188, level: 3, korean: '사고 소식을 들은 그녀는 곧바로 병원으로 달려갔어요.', wordOrder: ['들은 후', '사고 소식을', '그녀는 달려갔어요', '곧바로 병원으로'], hints: ['upon hearing', 'the news of the accident', 'rushed', 'to the hospital'], answer: 'Upon hearing the news of the accident, she rushed to the hospital.' },
  { id: 189, level: 3, korean: '시간이 지나면 지날수록 그 기억은 더 아름다워져요.', wordOrder: ['시간이 지날수록', '그 기억은', '더 아름다워져요'], hints: ['as time goes by', 'the memory', 'becomes more beautiful'], answer: 'As time goes by, the memory becomes more beautiful.' },
  { id: 190, level: 3, korean: '여기서 볼 수 있는 풍경은 세계 어디에서도 찾기 어려워요.', wordOrder: ['풍경은', '여기서 볼 수 있는', '찾기 어려워요', '세계 어디에서도'], hints: ['the scenery', 'you can see here', 'hard to find', 'anywhere else in the world'], answer: 'The scenery you can see here is hard to find anywhere else in the world.' },
  { id: 191, level: 3, korean: '그는 성공할 때까지 절대 포기하지 않겠다고 다짐했어요.', wordOrder: ['그는 다짐했어요', '절대 포기하지 않겠다고', '성공할 때까지'], hints: ['vowed', 'never to give up', 'until he succeeded'], answer: 'He vowed never to give up until he succeeded.' },
  { id: 192, level: 3, korean: '잠을 충분히 자지 못한 채로 일하면 실수가 많아져요.', wordOrder: ['만약 일하면', '자지 못한 채로', '충분히', '실수가 많아져요'], hints: ['if you work', 'without getting enough', 'sleep', 'you make more mistakes'], answer: 'If you work without getting enough sleep, you make more mistakes.' },
  { id: 193, level: 3, korean: '10년 전에 심은 나무가 지금은 아주 크게 자랐어요.', wordOrder: ['나무가', '10년 전에 심은', '자랐어요', '아주 크게', '지금은'], hints: ['the tree', 'planted ten years ago', 'has grown', 'very big', 'now'], answer: 'The tree planted ten years ago has now grown very big.' },
  { id: 194, level: 3, korean: '우리가 당연하게 여기는 것들이 사실은 가장 소중한 거예요.', wordOrder: ['것들이', '우리가 당연하게 여기는', '사실은', '가장 소중한 거예요'], hints: ['the things', 'we take for granted', 'are actually', 'the most precious'], answer: 'The things we take for granted are actually the most precious.' },
  { id: 195, level: 3, korean: '다른 나라의 문화를 체험하는 것은 시야를 넓혀 줘요.', wordOrder: ['체험하는 것은', '다른 나라의 문화를', '넓혀 줘요', '시야를'], hints: ['experiencing', 'other cultures', 'broadens', 'your perspective'], answer: 'Experiencing other cultures broadens your perspective.' },
  { id: 196, level: 3, korean: '그녀가 만든 작품은 많은 사람들에게 영감을 주었어요.', wordOrder: ['작품은', '그녀가 만든', '영감을 주었어요', '많은 사람들에게'], hints: ['the work', 'she created', 'inspired', 'many people'], answer: 'The work she created inspired many people.' },
  { id: 197, level: 3, korean: '내가 처음 이곳에 왔을 때는 아무것도 없는 빈 땅이었어요.', wordOrder: ['이곳에 왔을 때', '내가 처음', '이곳은 이었어요', '아무것도 없는 빈 땅'], hints: ['when I first came here', 'this place was', 'an empty lot', 'with nothing'], answer: 'When I first came here, this place was an empty lot with nothing.' },
  { id: 198, level: 3, korean: '성공이란 실패를 거듭하면서도 열정을 잃지 않는 것이에요.', wordOrder: ['성공이란', '열정을 잃지 않는 것이에요', '거듭하면서도', '실패를'], hints: ['success is', 'not losing your passion', 'even after repeated', 'failures'], answer: 'Success is not losing your passion even after repeated failures.' },
  { id: 199, level: 3, korean: '그가 쓴 편지를 읽고 나서야 그의 진심을 알 수 있었어요.', wordOrder: ['읽고 나서야', '그가 쓴 편지를', '알 수 있었어요', '그의 진심을'], hints: ['only after reading', 'the letter he wrote', 'could I understand', 'his true feelings'], answer: 'Only after reading the letter he wrote could I understand his true feelings.' },
  { id: 200, level: 3, korean: '우리가 함께 보낸 시간은 내 인생에서 가장 행복한 순간이었어요.', wordOrder: ['시간은', '우리가 함께 보낸', '가장 행복한 순간이었어요', '내 인생에서'], hints: ['the time', 'we spent together', 'the happiest moments', 'in my life'], answer: 'The time we spent together was the happiest moments in my life.' },
];

export const getSentencesByLevel = (level: 1 | 2 | 3): Sentence[] => {
  return sentences.filter((s) => s.level === level);
};
